###
GET http://localhost:5257

###

GET http://localhost:5257/api/produto/listar
###

POST  http://localhost:5257/api/produto/cadastrar
Content-Type: application/json

{
    "nome":"Chama",
    "quantidade": 50,
    "preco": 85.05
}

###
GET http://localhost:5257/api/produto/listar

###
DELETE http://localhost:5257/api/produto/remover/

###
PATCH http://localhost:5257/api/produto/alterar/a66a6553-8a4b-4ad7-90eb-6817978353b0
Content-Type: application/json

{
    "nome":"TetS",
    "quantidade": 5080,
    "preco": 90.05
}